### ISSUE TITLE
sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by javierxz** [danielcardeenas/MacBot#7]
I have issue, please help to solve!
error code is:
```
Traceback (most recent call last):
  File "/root/MacBot/run.py", line 9, in <module>
    from layer import MacLayer
  File "/root/MacBot/layer.py", line 5, in <module>
    from app import main
  File "/root/MacBot/app/main.py", line 10, in <module>
    from app.elo import elo, match
  File "/root/MacBot/app/elo/elo.py", line 6, in <module>
    conn = sqlite3.connect('app/elo/db/trueskill.db')
sqlite3.OperationalError: unable to open database file
```

**Comment by javierxz** [comment]
> SOLVED
Change db location to /root/MacBot/app/elo/db/trueskill.db on elo.py
